# Generated by Django 3.2.8 on 2024-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('year', models.PositiveSmallIntegerField()),
                ('gdp', models.FloatField()),
            ],
        ),
    ]
